/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Armbian_Meter
#define HEADER_Armbian_Meter
/*
htop - Armbianversion_Meter.h
(C) 2018 @lex
*/

#include "Meter.h"

extern int Armbianversion_Meter_attributes[];

extern MeterClass Armbianversion_Meter_class;


#endif
