/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_BlockDevice_ioStatsMeter
#define HEADER_BlockDevice_ioStatsMeter
/*
htop - BlockDevice_ioStatsMeter.h
(C) 2020 @lex
*/

#include "Meter.h"

extern int BlockDevice_ioStatsMeter_attributes[];

extern MeterClass BlockDevice_sda_ioStatsMeter_class;

extern MeterClass BlockDevice_sdb_ioStatsMeter_class;

extern MeterClass BlockDevice_sdc_ioStatsMeter_class;

extern MeterClass BlockDevice_sdd_ioStatsMeter_class;

extern MeterClass BlockDevice_mmcblk0_ioStatsMeter_class;

extern MeterClass BlockDevice_mmcblk1_ioStatsMeter_class;

extern MeterClass BlockDevice_mmcblk2_ioStatsMeter_class;

extern MeterClass BlockDevice_mmcblk3_ioStatsMeter_class;


#endif
