/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_CpuVcoreMeter
#define HEADER_CpuVcoreMeter
/*
htop - CpuVcoreMeter.h
(C) 2020 Alexander Finger
*/

#include "Meter.h"

extern int CpuVcoreMeter_attributes[];

extern MeterClass CpuVcoreMeter_class;

#endif
