/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Eth0_StatsMeter
#define HEADER_Eth0_StatsMeter
/*
htop - Eth0_StatsMeter.h
(C) 2020 @lex
*/

#include "Meter.h"

extern int Eth0_StatsMeter_attributes[];

/* borrowed from slurm */
extern MeterClass Eth0_StatsMeter_class;


#endif
