/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Eth0_Meter
#define HEADER_Eth0_Meter
/*
htop - Eth0_Meter.h
(C) 2018 @lex
*/

#include "Meter.h"

extern int Eth0_Meter_attributes[];

extern MeterClass Eth0_Meter_class;


#endif
