/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Eth1_Meter
#define HEADER_Eth1_Meter
/*
htop - Eth1_Meter.h
(C) 2018 @lex
*/

#include "Meter.h"

extern int Eth1_Meter_attributes[];

extern MeterClass Eth1_Meter_class;


#endif
