/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Eth1_StatsMeter
#define HEADER_Eth1_StatsMeter
/*
htop - Eth1_StatsMeter.h
(C) 2020 @lex
*/

#include "Meter.h"

extern int Eth1_StatsMeter_attributes[];

/* borrowed from slurm */
extern MeterClass Eth1_StatsMeter_class;


#endif
