/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_GpuTempMeter
#define HEADER_GpuTempMeter
/*
htop - GpuTempMeter.h
(C) 2018 @lex
*/

#include "Meter.h"

extern int GpuTempMeter_attributes[];

extern MeterClass GpuTempMeter_class;

#endif
