/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_interfaces
#define HEADER_interfaces

#define BLEN 256
/*
    /etc/armbian-release
    VERSION=20.02.1

    /etc/debian_version
    buster/sid

    cat /etc/lsb-release
    DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

    cat /etc/os-release
    PRETTY_NAME="Ubuntu 18.04.5 LTS"
    VERSION="18.04.5 LTS (Bionic Beaver)"
    ID=ubuntu

    cat /proc/version
    Linux version 5.3.0-52-generic (buildd@lgw01-amd64-037) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #46~18.04.1-Ubuntu SMP Thu Apr 30 16:13:51 UTC 2020
*/

int ReadKeyValue( char *fname, char *key, char *value);

int ReadTokenValue( char *fname, char *key, char *value);

int findIP_interface(char *dev, char *szIP, int bufsz);

#endif
