/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Kernel_Meter
#define HEADER_Kernel_Meter
/*
htop - Kernelversion_Meter.h
(C) 2018 @lex
*/

#include "Meter.h"

extern int Kernelversion_Meter_attributes[];

extern MeterClass Kernelversion_Meter_class;


#endif
