/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_OS_Meter
#define HEADER_OS_Meter
/*
htop - OSversion_Meter.h
(C) 2018 @lex
*/

#include "Meter.h"

extern int OSversion_Meter_attributes[];

extern MeterClass OSversion_Meter_class;


#endif
