/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Settings
#define HEADER_Settings
/*
htop - Settings.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#define DEFAULT_DELAY 15

#include "Process.h"
#include <stdbool.h>

typedef struct {
   int len;
   char** names;
   int* modes;
} MeterColumnSettings;

typedef struct Settings_ {
   char* filename;
   
   MeterColumnSettings columns[2];

   ProcessField* fields;
   int flags;
   int colorScheme;
   int delay;

   int cpuCount;
   int direction;
   ProcessField sortKey;

   bool countCPUsFromZero;
   bool detailedCPUTime;
   bool treeView;
   bool showProgramPath;
   bool hideThreads;
   bool shadowOtherUsers;
   bool showThreadNames;
   bool hideKernelThreads;
   bool hideUserlandThreads;
   bool highlightBaseName;
   bool highlightMegabytes;
   bool highlightThreads;
   bool updateProcessNames;
   bool accountGuestInCPUMeter;
   bool headerMargin;

   char CpuFreq_handler[256]; 
   char CpuTemp_handler[256]; 
   char CpuVCore_l_handler[256];
   char CpuVCore_b_handler[256];
   
   char GpuVCore_handler[256];
   char GpuTemp_handler[256];
   
   char BoardName[128];
   char KernelVersionFull[256];
   char KernelVersionShort[64];
   
   char IP_wlan0[32];
   char IP_wlan1[32];
   char IP_eth0[32];
   char IP_eth1[32];
   
   char eth0_alias[32];
   char eth1_alias[32];
   char wlan0_alias[32];
   char wlan1_alias[32];

   bool changed;
} Settings;

#ifndef Settings_cpuId
#define Settings_cpuId(settings, cpu) ((settings)->countCPUsFromZero ? (cpu) : (cpu)+1)
#endif


void Settings_delete(Settings* this);

bool Settings_write(Settings* this);

Settings* Settings_new(int cpuCount);

void Settings_invertSortOrder(Settings* this);

#endif
