/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Wlan0_StatsMeter
#define HEADER_Wlan0_StatsMeter
/*
htop - Wlan0_StatsMeter.h
(C) 2020 @lex
*/

#include "Meter.h"

extern int Wlan0_StatsMeter_attributes[];

/* borrowed from slurm */
extern MeterClass Wlan0_StatsMeter_class;


#endif
