/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Wlan1_Meter
#define HEADER_Wlan1_Meter
/*
htop - Eth0_Meter.h
(C) 2018 @lex
*/

#include "Meter.h"

extern int Wlan1_Meter_attributes[];

extern MeterClass Wlan1_Meter_class;


#endif
