/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Wlan0_Meter
#define HEADER_Wlan0_Meter
/*
htop - Wlan0_Meter.h
(C) 2020 @lex
*/

#include "Meter.h"

extern int Wlan0_Meter_attributes[];

extern MeterClass Wlan0_Meter_class;


#endif
